  version: "3"
  services: 
    server: 
      image: "kmjayadeep/dailytasks-server"
      build: .
      ports: 
        - "4000:4000"
    mysql:
      image: "mysql"
      command: --default-authentication-plugin=mysql_native_password
      ports:
        - "3306:3306"
      environment:
        MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

